version: '3'

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    tty: true
    command: ./serve.sh
    environment:
      API_URL: http://api:8000/v1/
      CYPRESS_API_URL: http://api:8000/v1/
    depends_on:
      - api
  db:
    image: postgres:13.2
    environment:
     POSTGRES_USER: ci_dev
     POSTGRES_PASSWORD: password
     POSTGRES_DB: ci_dev
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.9

  api:
    image: ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}/ci_api:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ENV: 'ci'
      DATABASE_NAME: ci_dev
      DATABASE_USER: ci_dev
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      EMAIL_VALIDATION_FQDN: "email_validator:8081"
      REDIS_URL: redis://redis:6379
    command: /start_api.sh

  email_validator:
    image: ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}/ci_validation
    ports:
      - 8081:8081
volumes:
  db_data:
